nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: KDTI
            description: This is an awesome app!
            version: 1.0.0
#        securityDefinitions:
#            Bearer:
#                type: apiKey
#                description: 'Value: Bearer {jwt}'
#                name: Authorization
#                in: header
#        security:
#            -   Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
