sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        attach_stacktrace: true 
        before_breadcrumb: '@sentry.callback.before_breadcrumb'
        before_send: '@sentry.callback.before_send'
        capture_silenced_errors: false
        context_lines: 5
        default_integrations: true 
        enable_compression: true
        environment: '%kernel.environment%'
        error_types: 'E_ALL & ~E_NOTICE'
        http_proxy: '10.0.0.12:3456'
        in_app_exclude:
          - '%kernel.cache_dir%'
          - '%kernel.project_dir%/vendor'
        integrations: 
          - '@sentry.integration.my_custom_integration'
        excluded_exceptions: 
          - 'My\Exceptions\IgnorableException'
        logger: 'php'
        max_breadcrumbs: 50 
        max_value_length: 2048
        prefixes:
          - '/local_dir/' 
        project_root: '%kernel.project_dir%'
        sample_rate: 1
        send_attempts: 3 
        send_default_pii: true 
        server_name: 'api.kdti.dev'
    listener_priorities:
        request: 1
        subrequest: 1
        console: 1